[build]
  base = "/client"
  command = "pnpm install --frozen-lockfile && pnpm run build"
  publish = "client/dist"

[context.production.environment]
  NODE_VERSION = "18.20.0"
  COREPACK_ENABLED = "true"

[context.production]
  command = "pnpm install --frozen-lockfile && pnpm run build"
